### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by renyu-renyu** [lyhkevin/MT-Net#2]
![image](https://github.com/lyhkevin/MT-Net/assets/88662555/78343916-5fb2-4886-a6d0-f7aa1e257d42)

**Comment by renyu-renyu** [comment]
请问你的这个模型怎么训练

**Comment by lyhkevin** [comment]
您好，这个表示数据还没有预处理好，请重新clone一下repo，然后到Kaggle下载数据（https://www.kaggle.com/datasets/awsaf49/brats20-dataset-training-validation?resource=download），接着根据ReadMe中的内容进行数据的预处理与模型的训练，谢谢！

**Comment by lyhkevin** [comment]
您好，这个表示数据还没有预处理好，请重新clone一下repo，然后到Kaggle下载BraTS2020数据集，接着根据ReadMe中的内容进行数据的预处理与模型的训练，谢谢！数据集的链接：https://www.kaggle.com/datasets/awsaf49/brats20-dataset-training-validation?resource=download

**Comment by renyu-renyu** [comment]
数据集需要解压放进去吗？

**Comment by lyhkevin** [comment]
> 

需要的，解压放到data文件夹，然后运行utils里面的preprocessing.py
