### ISSUE TITLE
About data preprocessing.

### ISSUE THREAD

**Issue by Kimiraha** [lyhkevin/MT-Net#3]
作者你好，

我看到utils/preprocessing.py中将BraTS的TrainingData二八分作为了测试集和训练集，
想请教为什么不用BraTS提供的ValidationData做测试，
另外论文中描述为用70%的训练数据来训练，这里为什么二八分呢？

**Comment by lyhkevin** [comment]
您好！

论文的实验部分，我们进行了肿瘤分割相关的工作 (见Fig. 12)，具体来说，就是用使用训练集(80%)训练好的模型，在测试集(20%)上生成目标模态(T2)的图像，并使用生成的测试集图像作为肿瘤分割网络的测试数据，从而评估肿瘤分割网络的性能。由于BraTS的Validation Data中不包含肿瘤的标签，因此，没有使用这批数据进行训练或者测试。

二八分指的是将BraTS的训练集分为训练集（80%）和测试集（20%），我们先使用这80%的数据先进行了模型的预训练。此后，我们再在80%的训练集中只取70%的数据进行模型的微调。这是为了测试提出的模型在数据不完全成对的情况下的表现(只有部分数据有对应的Ground truth)。

如果只是验证生成图像的质量，您可以修改代码，按照BraTS的数据集划分进行实验。

谢谢！

**Comment by Kimiraha** [comment]
感谢回复，
我现在明白数据是怎样使用的了。

谢谢~
