### ISSUE TITLE
About pretrain

### ISSUE THREAD

**Issue by VLAD-KONATA** [lyhkevin/MT-Net#4]
发生异常: ValueError
cannot reshape array of size 0 into shape (5,200,200)
  File "E:\MT-Net Data\MT-Net\utils\maeloader.py", line 98, in __getitem__
    npy = np.load(self.images[subject])
  File "E:\MT-Net Data\MT-Net\pretrain.py", line 42, in <module>
    for i,img in enumerate(train_loader):
ValueError: cannot reshape array of size 0 into shape (5,200,200)

总是pretrain一部分以后报这个错误，不知道是什么情况

**Comment by lyhkevin** [comment]
The input size for our Edge-MAE should be 256*256

**Comment by VLAD-KONATA** [comment]
> The input size for our Edge-MAE should be 256*256

哦不好意思，我再去修改一下，应该是preprocessing出了问题

**Comment by VLAD-KONATA** [comment]
[Errno 13] Permission denied: 'D:/Git/MT-Net/weight/'
  File "D:\Git\MT-Net\test.py", line 32, in <module>
    E.load_state_dict(torch.load(opt.E_path, map_location=torch.device(device)),strict=False)
PermissionError: [Errno 13] Permission denied: 'D:/Git/MT-Net/weight/'

**Comment by lyhkevin** [comment]
This happens if you are trying to open a file, but your path is a folder ('D:/Git/MT-Net/weight/').  Instead, load the path (.pth file)

**Comment by VLAD-KONATA** [comment]
> This happens if you are trying to open a file, but your path is a folder ('D:/Git/MT-Net/weight/'). Instead, load the path (.pth file)

thanks, it helps me a lot 😂
